"use client";
import { useState, useRef } from "react";
import Link from "next/link";

interface Writer {
  id: number;
  name: string;
  role: string;
  split: string;
  pro: string;
  ipi: string;
}

const ROLES = ["Songwriter", "Co-writer", "Composer", "Lyricist", "Producer", "Topliner", "Beat Maker"];
const PROS  = ["ASCAP", "BMI", "SESAC", "SOCAN", "PRS", "GEMA", "SACEM", "Other", "None"];

let nextId = 3;

export default function SplitSheetPage() {
  const [songTitle, setSongTitle]     = useState("");
  const [artistName, setArtistName]   = useState("");
  const [recordedBy, setRecordedBy]   = useState("");
  const [sessionDate, setSessionDate] = useState("");
  const [isrc, setIsrc]               = useState("");

  const [writers, setWriters] = useState<Writer[]>([
    { id: 1, name: "", role: "Songwriter", split: "", pro: "ASCAP", ipi: "" },
    { id: 2, name: "", role: "Songwriter", split: "", pro: "BMI",   ipi: "" },
  ]);

  const printRef = useRef<HTMLDivElement>(null);

  const addWriter = () => {
    setWriters(w => [...w, { id: nextId++, name: "", role: "Songwriter", split: "", pro: "ASCAP", ipi: "" }]);
  };
  const removeWriter = (id: number) => setWriters(w => w.filter(x => x.id !== id));
  const updateWriter = (id: number, field: keyof Writer, value: string) =>
    setWriters(w => w.map(x => x.id === id ? { ...x, [field]: value } : x));

  const total = writers.reduce((s, w) => s + (parseFloat(w.split) || 0), 0);
  const totalOk = Math.abs(total - 100) < 0.01;

  const canDownload = songTitle && writers.some(w => w.name && w.split) && totalOk;

  const handlePrint = () => {
    const el = printRef.current;
    if (!el) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head><title>Split Sheet — ${songTitle}</title>
      <style>
        body { font-family: -apple-system, sans-serif; padding: 40px; color: #111; max-width: 700px; margin: 0 auto; }
        h1 { font-size: 24px; font-weight: 900; margin-bottom: 4px; }
        .sub { color: #666; font-size: 14px; margin-bottom: 32px; }
        .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 32px; }
        .meta-item label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; color: #888; display: block; margin-bottom: 2px; }
        .meta-item span { font-size: 15px; font-weight: 600; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 32px; }
        th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: #888; padding: 8px 12px; border-bottom: 2px solid #eee; }
        td { padding: 10px 12px; border-bottom: 1px solid #f0f0f0; font-size: 14px; }
        tr:last-child td { border-bottom: none; }
        .total-row td { font-weight: 700; background: #f9f9f9; border-top: 2px solid #eee; }
        .ok { color: #00a87a; }
        .warn { color: #e63946; }
        .sigs { margin-top: 40px; }
        .sig-block { border-top: 1px solid #ccc; margin-top: 32px; padding-top: 8px; }
        .sig-label { font-size: 12px; color: #888; }
        .legal { font-size: 11px; color: #aaa; margin-top: 48px; line-height: 1.6; border-top: 1px solid #eee; padding-top: 16px; }
        @media print { body { padding: 20px; } }
      </style></head><body>
      <h1>Split Sheet</h1>
      <div class="sub">Songwriter Ownership Agreement — Generated by MusicRight.AI</div>
      <div class="meta">
        <div class="meta-item"><label>Song Title</label><span>${songTitle || "—"}</span></div>
        <div class="meta-item"><label>Artist / Recording Name</label><span>${artistName || "—"}</span></div>
        <div class="meta-item"><label>Recorded By</label><span>${recordedBy || "—"}</span></div>
        <div class="meta-item"><label>Session Date</label><span>${sessionDate || "—"}</span></div>
        ${isrc ? `<div class="meta-item"><label>ISRC</label><span>${isrc}</span></div>` : ""}
        <div class="meta-item"><label>Date Generated</label><span>${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</span></div>
      </div>
      <table>
        <thead><tr><th>#</th><th>Full Name</th><th>Role</th><th>PRO</th><th>IPI Number</th><th>Split %</th></tr></thead>
        <tbody>
          ${writers.filter(w => w.name).map((w, i) => `
            <tr><td>${i + 1}</td><td><strong>${w.name}</strong></td><td>${w.role}</td><td>${w.pro}</td><td>${w.ipi || "—"}</td><td><strong>${w.split}%</strong></td></tr>
          `).join("")}
          <tr class="total-row"><td colspan="5">TOTAL</td><td class="${totalOk ? "ok" : "warn"}">${total.toFixed(2)}%</td></tr>
        </tbody>
      </table>
      <div class="sigs">
        <p style="font-size:14px;color:#444;margin-bottom:24px;">By signing below, each party confirms they are the rightful owner of the percentage listed above and agrees to the terms of this split sheet.</p>
        ${writers.filter(w => w.name).map(w => `
          <div class="sig-block">
            <strong>${w.name}</strong> — ${w.split}% (${w.role})<br>
            <div style="margin-top:24px;border-bottom:1px solid #ccc;width:280px;"></div>
            <div class="sig-label">Signature &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date</div>
          </div>
        `).join("")}
      </div>
      <div class="legal">
        This split sheet documents the agreed songwriter ownership percentages for the above-referenced composition.
        All parties confirm that splits add to 100% and that no ownership claim is in dispute.
        This document does not constitute a master recording agreement, sync license, or publishing contract.
        Generated by MusicRight.AI — musicright.ai
      </div>
      </body></html>
    `);
    win.document.close();
    win.focus();
    setTimeout(() => { win.print(); win.close(); }, 400);
  };

  return (
    <div className="min-h-screen bg-[#080808] text-white">
      <nav className="fixed top-0 inset-x-0 z-50 border-b border-white/5 bg-[#080808]/90 backdrop-blur-xl">
        <div className="max-w-5xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md bg-gradient-to-br from-[#00d4aa] to-[#00b4d8]" />
            <span className="font-bold text-sm">MusicRight<span className="text-[#00d4aa]">.AI</span></span>
          </Link>
          <div className="flex items-center gap-4">
            <Link href="/tools" className="text-[#555] text-sm hover:text-white transition-colors">← All Tools</Link>
            <button onClick={handlePrint} disabled={!canDownload}
              className="h-8 px-4 rounded-lg bg-[#00d4aa] text-[#080808] text-xs font-bold hover:bg-[#00b894] transition-colors disabled:opacity-40 disabled:cursor-not-allowed">
              Download PDF
            </button>
          </div>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 pt-24 pb-20">
        <div className="mb-8">
          <Link href="/tools" className="text-[#555] text-sm hover:text-[#a0a0a0] mb-4 block">← All Tools</Link>
          <h1 className="text-3xl md:text-4xl font-black tracking-tight mb-3">Split Sheet Generator</h1>
          <p className="text-[#a0a0a0] text-base">
            Document songwriter splits before you leave the session. Download as a signed PDF — then register with your PRO and MLC.
          </p>
        </div>

        {/* Song info */}
        <div className="rounded-2xl border border-[#1a1a1a] bg-[#0e0e0e] p-6 mb-5">
          <h2 className="text-sm font-bold text-white uppercase tracking-wider mb-5">Song Info</h2>
          <div className="grid sm:grid-cols-2 gap-4">
            {[
              { label: "Song title *",        value: songTitle,    set: setSongTitle,    placeholder: "e.g. So Hot (feat. KTTeddy)" },
              { label: "Artist / Recording",  value: artistName,   set: setArtistName,   placeholder: "e.g. KTTeddy" },
              { label: "Recorded by",         value: recordedBy,   set: setRecordedBy,   placeholder: "Studio name or engineer" },
              { label: "Session date",        value: sessionDate,  set: setSessionDate,  placeholder: "", type: "date" },
              { label: "ISRC (optional)",     value: isrc,         set: setIsrc,         placeholder: "US-XXX-26-00001" },
            ].map(({ label, value, set, placeholder, type }) => (
              <div key={label}>
                <label className="text-[#555] text-[10px] font-bold uppercase tracking-wider mb-1.5 block">{label}</label>
                <input type={type ?? "text"} value={value} onChange={e => set(e.target.value)} placeholder={placeholder}
                  className="w-full h-10 bg-[#111] border border-[#2e2e2e] rounded-lg px-3 text-white text-sm placeholder-[#555] focus:outline-none focus:border-[#00d4aa]/50 transition-colors" />
              </div>
            ))}
          </div>
        </div>

        {/* Writers */}
        <div className="rounded-2xl border border-[#1a1a1a] bg-[#0e0e0e] p-6 mb-5">
          <div className="flex items-center justify-between mb-5">
            <h2 className="text-sm font-bold text-white uppercase tracking-wider">Songwriters & Splits</h2>
            <button onClick={addWriter} className="text-[#00d4aa] text-xs font-semibold hover:underline">+ Add writer</button>
          </div>

          <div className="flex flex-col gap-3">
            {writers.map((w, i) => (
              <div key={w.id} className="rounded-xl border border-[#1a1a1a] bg-[#111] p-4">
                <div className="flex items-center justify-between mb-3">
                  <span className="text-[#555] text-xs font-semibold">Writer {i + 1}</span>
                  {writers.length > 1 && (
                    <button onClick={() => removeWriter(w.id)} className="text-[#555] text-xs hover:text-[#ff4757]">Remove</button>
                  )}
                </div>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                  <div className="col-span-2 sm:col-span-1">
                    <label className="text-[#555] text-[10px] uppercase tracking-wider mb-1 block">Full legal name *</label>
                    <input value={w.name} onChange={e => updateWriter(w.id, "name", e.target.value)} placeholder="Full name"
                      className="w-full h-9 bg-[#0e0e0e] border border-[#2e2e2e] rounded-lg px-3 text-white text-sm placeholder-[#555] focus:outline-none focus:border-[#00d4aa]/50" />
                  </div>
                  <div>
                    <label className="text-[#555] text-[10px] uppercase tracking-wider mb-1 block">Role</label>
                    <select value={w.role} onChange={e => updateWriter(w.id, "role", e.target.value)}
                      className="w-full h-9 bg-[#0e0e0e] border border-[#2e2e2e] rounded-lg px-3 text-white text-sm focus:outline-none focus:border-[#00d4aa]/50">
                      {ROLES.map(r => <option key={r} value={r}>{r}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="text-[#555] text-[10px] uppercase tracking-wider mb-1 block">Split % *</label>
                    <input type="number" min="0" max="100" step="0.01" value={w.split} onChange={e => updateWriter(w.id, "split", e.target.value)} placeholder="50"
                      className="w-full h-9 bg-[#0e0e0e] border border-[#2e2e2e] rounded-lg px-3 text-white text-sm placeholder-[#555] focus:outline-none focus:border-[#00d4aa]/50" />
                  </div>
                  <div>
                    <label className="text-[#555] text-[10px] uppercase tracking-wider mb-1 block">PRO</label>
                    <select value={w.pro} onChange={e => updateWriter(w.id, "pro", e.target.value)}
                      className="w-full h-9 bg-[#0e0e0e] border border-[#2e2e2e] rounded-lg px-3 text-white text-sm focus:outline-none focus:border-[#00d4aa]/50">
                      {PROS.map(p => <option key={p} value={p}>{p}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="text-[#555] text-[10px] uppercase tracking-wider mb-1 block">IPI # (optional)</label>
                    <input value={w.ipi} onChange={e => updateWriter(w.id, "ipi", e.target.value)} placeholder="00000000000"
                      className="w-full h-9 bg-[#0e0e0e] border border-[#2e2e2e] rounded-lg px-3 text-white text-sm placeholder-[#555] focus:outline-none focus:border-[#00d4aa]/50" />
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Split total indicator */}
          <div className={`mt-4 flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-bold ${
            totalOk ? "bg-[#00d4aa]/10 text-[#00d4aa]" :
            total > 100 ? "bg-[#ff4757]/10 text-[#ff4757]" :
            "bg-[#ffb800]/10 text-[#ffb800]"
          }`}>
            <span>{totalOk ? "✓" : total > 100 ? "✗" : "○"}</span>
            <span>Total: {total.toFixed(1)}%</span>
            {!totalOk && <span className="font-normal text-xs">— must equal 100%</span>}
          </div>
        </div>

        {/* Actions */}
        <div className="flex gap-3 flex-wrap">
          <button onClick={handlePrint} disabled={!canDownload}
            className="h-12 px-8 rounded-xl bg-[#00d4aa] text-[#080808] font-bold text-sm hover:bg-[#00b894] transition-colors disabled:opacity-40 disabled:cursor-not-allowed">
            Download Split Sheet PDF
          </button>
          <Link href="/start"
            className="h-12 px-6 rounded-xl border border-[#00d4aa]/20 bg-[#00d4aa]/5 text-[#00d4aa] font-semibold text-sm flex items-center hover:bg-[#00d4aa]/10 transition-colors">
            Register with PRO & MLC →
          </Link>
        </div>

        {/* Info */}
        <div className="mt-6 rounded-xl border border-[#1a1a1a] bg-[#0a0a0a] p-4 text-[#555] text-xs leading-relaxed">
          <strong className="text-[#a0a0a0]">70% of indie artists have had a split dispute.</strong> A signed split sheet is your first line of defense.
          After downloading: get every writer&apos;s signature, then register the song with your PRO (ASCAP/BMI/SESAC) and The MLC using the percentages documented here.
        </div>

        {/* Hidden print div */}
        <div ref={printRef} className="hidden" />
      </div>
    </div>
  );
}
